---
- hosts:
   - f-pc5844-debian13.fritz.box
   - ver-kruegeol007.germany.focke.de
   - F-PC5844-pop-os.fritz.box
  become: true
#  become_method: enable
  tasks:
    - name: Update the repository cache and update package freecad to latest version using default release
      ansible.builtin.apt:
        name: freecad
        state: latest
#    default_release: squeeze-backports
        update_cache: yes

 
